In [7]:
import numpy as np

In [16]:
li=[1,2,3,4]
a = np.array(li,dtype=float)
print(a)

[1. 2. 3. 4.]


In [18]:
li=[1,2,3,4]
a= np.array(li,dtype=int)
a

array([1, 2, 3, 4])

In [19]:
li=[1,2,3,4,5]
a= np.array(li,dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

# WE CAN'T MAKE COMPLEX to (int,float)

# Dimensions in Array
 0-D Array

In [22]:
arr=np.array(1000)
print("Show Array is: ",arr)
print("Dimension of array is: ",arr.ndim)
#ndim= no. of dimensions.

Show Array is:  1000
Dimension of array is:  0


# 1-D Array

In [26]:
a = np.array([1000])
print("Show Array is: ", a)
print("Dimenshion of array is: ", a.ndim)

Show Array is:  [1000]
Dimenshion of array is:  1


In [33]:
a= np.array([1000],float)
print("Show Array is: ",a)
print("Dimenshion of array is: ", a.ndim)
a= np.array([10.0],int)
print("Show Array is: ",a)
print("Dimenshion of array is: ", a.ndim)
a= np.array([1000],complex)
print("Show Array is: ",a)
print("Dimenshion of array is: ", a.ndim)

Show Array is:  [1000.]
Dimenshion of array is:  1
Show Array is:  [10]
Dimenshion of array is:  1
Show Array is:  [1000.+0.j]
Dimenshion of array is:  1


In [35]:
a = np.array([200,100,300,400])
print("Show Array is: ",a)
print("Dimenshion of array is: ", a.ndim)
#becuase its in one bracket only

Show Array is:  [200 100 300 400]
Dimenshion of array is:  1


In [57]:
#for shape
a= np.array([[10,20],[30,40]])
print("Show Array is: \n ",a)
print("Dimenshion of array is: ", a.ndim)
print("Shape of Array is: ",a.shape)

Show Array is: 
  [[10 20]
 [30 40]]
Dimenshion of array is:  2
Shape of Array is:  (2, 2)


# If Outer bracket is '3' then (3-D)
        &
# If Outer bracket is '2' then (2-D)

# 2-D Array:

In [47]:
a= np.array([[10],[20]])
print("Show Array is:\n ",a)
print("Dimenshion of array is: ", a.ndim)
print("Shape of Array: ",a.shape)

Show Array is:
  [[10]
 [20]]
Dimenshion of array is:  2
Shape of Array:  (2, 1)


# here shape (2='row', 1='column')

In [53]:
a= np.array([[10,20]])
print("Show Array is: \n ",a)
print("Dimenshion of array is: ", a.ndim)
print("Shape of Array is: ",a.shape)

Show Array is: 
  [[10 20]]
Dimenshion of array is:  2
Shape of Array is:  (1, 2)


In [60]:
#for 1-'row', 2-'column'
a= np.array([[10,20]])
print("Show Array is: \n ",a)
print("Dimenshion of array is: ", a.ndim)
print("Shape of Array is: ",a.shape)

Show Array is: 
  [[10 20]]
Dimenshion of array is:  2
Shape of Array is:  (1, 2)


# 3-D Array

In [67]:
a = np.array([[[10,20],[30,40],[40,50]]])
print("Show Array is: \n ",a)
print("Dimenshion of array is: ", a.ndim)
print("Shape of Array is: ",a.shape)

#for showing 2 element in shape of arr
#mhanje 2-D chi 1 array aste!
a = np.array([[[10,20],[30,40],[40,50]],[[10,20],[30,40],[40,50]]])
print("Show Array is: \n ",a)
print("Dimenshion of array is: ", a.ndim)
print("Shape of Array is: ",a.shape)

Show Array is: 
  [[[10 20]
  [30 40]
  [40 50]]]
Dimenshion of array is:  3
Shape of Array is:  (1, 3, 2)
Show Array is: 
  [[[10 20]
  [30 40]
  [40 50]]

 [[10 20]
  [30 40]
  [40 50]]]
Dimenshion of array is:  3
Shape of Array is:  (2, 3, 2)


### Indexing and Slicing

In [ ]:
a=np